{
    "openapi": "3.0.1",
    "info": {
        "title": "Products",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "To prepare for an upcoming product launch, use the products API to create a set of products to represent your new offerings. Sales reps can then use these products when creating payment links, invoices, and more.",
        "x-hubspot-related-documentation": [
            {
                "name": "Products Guide",
                "url": "https://developers.hubspot.com/beta-docs/guides/api/crm/objects/products"
            }
        ],
        "x-hubspot-introduction": "Use the products API to create and manage your product library, which is the collection of goods and services that your company offers. Products in your product library can be used as line items when creating deals, payment links, invoices, and quotes."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com/crm/v3/objects/products"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/batch/read": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Read products by ID or property",
                "operationId": "post-/batch/read_read",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    }
                ],
                "description": "Returns a batch of products matching the provided internal IDs or unique property values, with partial success indicated by a 207 response."
            }
        },
        "/{productId}": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Retrieve a product by ID",
                "description": "Read an Object identified by `{productId}`. `{productId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
                "operationId": "get-/{productId}_getById",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Basic"
                ],
                "summary": "Archive a product by ID",
                "description": "Move an Object identified by `{productId}` to the recycling bin.",
                "operationId": "delete-/{productId}_archive",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Basic"
                ],
                "summary": "Partially update a product",
                "description": "Perform a partial update of an Object identified by `{productId}`. `{productId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.",
                "operationId": "patch-/{productId}_update",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    }
                ]
            }
        },
        "/batch/archive": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Archive a batch of products by ID",
                "operationId": "post-/batch/archive_archive",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    }
                ],
                "description": "Returns no content upon successfully archiving the specified batch of products."
            }
        },
        "/batch/create": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Create a batch of products",
                "operationId": "post-/batch/create_create",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    }
                ],
                "description": "Returns the newly created batch of products, with partial success indicated by a 207 response."
            }
        },
        "/batch/update": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Update a batch of products",
                "operationId": "post-/batch/update_update",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    }
                ],
                "description": "Returns the updated batch of products matched by internal ID or unique property values, with partial success indicated by a 207 response."
            }
        },
        "/": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Retrieve a page of products",
                "description": "Read a page of products. Control what is returned via the `properties` query param.",
                "operationId": "get-_getPage",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Basic"
                ],
                "summary": "Create a new product",
                "description": "Create a product with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard products is provided.",
                "operationId": "post-_create",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    }
                ]
            }
        },
        "/batch/upsert": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Upsert a batch of products",
                "description": "Create or update records identified by a unique property value as specified by the `idProperty` query param. `idProperty` query param refers to a property whose values are unique for the object.",
                "operationId": "post-/batch/upsert_upsert",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    }
                ]
            }
        },
        "/search": {
            "post": {
                "tags": [
                    "Search"
                ],
                "operationId": "post-/search_doSearch",
                "security": [
                    {
                        "oauth2_legacy": [
                            "e-commerce"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "e-commerce"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ],
                "description": "Returns a list of products matching the specified search criteria and filters.",
                "summary": "Search for products"
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.goals.read": "Read goals",
                            "tickets": "Read and write tickets",
                            "crm.objects.custom.read": "View custom object records",
                            "e-commerce": "e-commerce",
                            "crm.objects.custom.write": "Change custom object records",
                            "media_bridge.read": "Read media and media events"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.companies.write": " ",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.orders.read": "Read Orders",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.companies.read": " ",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.deals.read": " ",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.deals.write": " ",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.listings.write": "Write listings"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header",
                "x-ballerina-name": "privateAppLegacy"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header",
                "x-ballerina-name": "privateApp"
            }
        }
    },
    "x-hubspot-available-client-libraries": [
        "PHP",
        "Node",
        "Ruby",
        "Python"
    ],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "FREE"
    },
    "x-hubspot-documentation-banner": "NONE"
}